// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZnymkyHub.DAL.Persistence;

namespace ZnymkyHub.DAL.Migrations
{
    [DbContext(typeof(ZnymkyHubContext))]
    [Migration("20190404130307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("ReceiverId");

                    b.Property<int>("SenderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("PhotoId");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.FavouritePhotographer", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("PhotographerId");

                    b.HasKey("Id", "UserId", "PhotographerId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouritePhotographers");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Like", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("PhotoId");

                    b.HasKey("Id", "UserId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.OutgoingCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("OutgoingCities");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfLikes");

                    b.Property<int>("NumberOfSaving");

                    b.Property<int>("PhotographerId");

                    b.Property<int?>("PhotoshootId");

                    b.HasKey("Id");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("PhotoshootId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.PhotographerOutgoingCity", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("PhotographerId");

                    b.Property<int>("OutgoingCityId");

                    b.Property<int>("AdditionalPayment");

                    b.HasKey("Id", "PhotographerId", "OutgoingCityId");

                    b.HasIndex("OutgoingCityId");

                    b.HasIndex("PhotographerId");

                    b.ToTable("PhotographerOutgoingCities");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.PhotoResolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Medium");

                    b.Property<string>("Original");

                    b.Property<int>("PhotoId");

                    b.Property<string>("Small");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoResolutions");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Photoshoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PhotographerId");

                    b.Property<int>("PhotoshootTypeId");

                    b.HasKey("Id");

                    b.HasIndex("PhotoshootTypeId");

                    b.HasIndex("PhotographerId", "PhotoshootTypeId")
                        .IsUnique();

                    b.ToTable("Photoshoots");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.PhotoshootType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PhotoshootTypes");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Saving", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("PhotoId");

                    b.HasKey("Id", "UserId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Savings");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FacebookUrl");

                    b.Property<string>("FirstName");

                    b.Property<string>("HomeTown");

                    b.Property<string>("InstagramUrl");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePhoto");

                    b.Property<string>("ProfilePhotoName");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<int>("RoleId");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.UserPhotoshootType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("PhotographerId");

                    b.Property<int>("PhotoshootTypeId");

                    b.Property<int>("Price");

                    b.HasKey("Id", "PhotographerId", "PhotoshootTypeId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("PhotoshootTypeId");

                    b.ToTable("UserPhotoshootTypes");
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Photographer", b =>
                {
                    b.HasBaseType("ZnymkyHub.DAL.Core.Domain.User");

                    b.Property<int>("NumberOfPhotos");

                    b.ToTable("Photographer");

                    b.HasDiscriminator().HasValue("Photographer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Chat", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "Receiver")
                        .WithMany("ChatReceiver")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "Sender")
                        .WithMany("ChatSender")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Comment", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photo", "Photo")
                        .WithMany("Comments")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.FavouritePhotographer", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photographer", "Photographer")
                        .WithMany("FavouritePhotographerUsers")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "User")
                        .WithMany("FavouritePhotographerPhotographers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Like", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photo", "Photo")
                        .WithMany("Likes")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Photo", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photographer", "Photographer")
                        .WithMany("Photos")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photoshoot", "Photoshoot")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoshootId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.PhotographerOutgoingCity", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.OutgoingCity", "OutgoingCity")
                        .WithMany("PhotographerOutgoingCities")
                        .HasForeignKey("OutgoingCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photographer", "Photographer")
                        .WithMany("PhotographerOutgoingCities")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.PhotoResolution", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photo", "Photo")
                        .WithOne("PhotoResolution")
                        .HasForeignKey("ZnymkyHub.DAL.Core.Domain.PhotoResolution", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Photoshoot", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photographer", "Photographer")
                        .WithMany("Photoshoots")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.PhotoshootType", "PhotoshootType")
                        .WithMany("Photoshoots")
                        .HasForeignKey("PhotoshootTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.Saving", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photo", "Photo")
                        .WithMany("Savings")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.User", "User")
                        .WithMany("Savings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.User", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ZnymkyHub.DAL.Core.Domain.UserPhotoshootType", b =>
                {
                    b.HasOne("ZnymkyHub.DAL.Core.Domain.Photographer", "Photographer")
                        .WithMany("UserPhotoshootTypes")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZnymkyHub.DAL.Core.Domain.PhotoshootType", "PhotoshootType")
                        .WithMany("UserPhotoshootTypes")
                        .HasForeignKey("PhotoshootTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
